SAMPLES : ['SLX-19014.ATACAd001.HYTFKDRXX.s_1',
'SLX-19014.ATACAd001.HYTFKDRXX.s_2',
'SLX-19014.ATACAd003.HYTFKDRXX.s_1',
'SLX-19014.ATACAd003.HYTFKDRXX.s_2',
'SLX-19014.ATACAd004.HYTFKDRXX.s_1',
'SLX-19014.ATACAd004.HYTFKDRXX.s_2',
'SLX-19014.ATACAd005.HYTFKDRXX.s_1',
'SLX-19014.ATACAd005.HYTFKDRXX.s_2',
'SLX-19014.ATACAd006.HYTFKDRXX.s_1',
'SLX-19014.ATACAd006.HYTFKDRXX.s_2',
'SLX-19014.ATACAd007.HYTFKDRXX.s_1',
'SLX-19014.ATACAd007.HYTFKDRXX.s_2',
'SLX-19014.ATACAd008.HYTFKDRXX.s_1',
'SLX-19014.ATACAd008.HYTFKDRXX.s_2',
'SLX-19014.ATACAd009.HYTFKDRXX.s_1',
'SLX-19014.ATACAd009.HYTFKDRXX.s_2',
]

CHR : 'chrM'
GENOME: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/gatkresources/Homo_sapiens_assembly38.fasta"
INDEX: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/gatkresources/Homo_sapiens_assembly38"
