REPLICATE: ['SLX-19014.ATACAd001.HYTFKDRXX','SLX-19014.ATACAd002.HYTFKDRXX','SLX-19014.ATACAd003.HYTFKDRXX','SLX-19014.ATACAd004.HYTFKDRXX']
REPLICATE_NAME: 'replicate1' 
WORKDIR: '/rds/project/yhbl2/rds-yhbl2-genehunter/SM/BIC053/test'
CHR : 'chrM'
GENOME: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/Mus_musculus/Ensembl/GRCm38/Sequence/Bowtie2Index/genome"
INDEX: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/Mus_musculus/Ensembl/GRCm38/Sequence/Bowtie2Index/genome"
